[package]
name = "camera_bot"
version = "0.3.1"
authors = ["Guilherme Chichanoski <guilherme.chichanoski@gmail.com>", "Tiago Nascimento <tiago@theosirian.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
futures = "0.3"
serde = "1.0"
telegram-bot = { git = 'https://github.com/telegram-rs/telegram-bot' }
actix-web = "2.0"
actix-rt = "1.0"
lazy_static = "1.4.0"

[[bin]]
name = "camera_bot"
path = "src/main.rs"
